/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIGeneration {
  'id' : bigint,
  'goal' : string,
  'createdAt' : Timestamp,
  'tone' : string,
  'audience' : string,
  'platform' : string,
  'saved' : boolean,
  'userPrincipal' : UserId,
  'niche' : string,
  'outputText' : string,
  'favorite' : boolean,
}
export interface AIGenerationParams {
  'goal' : string,
  'tone' : string,
  'audience' : string,
  'platform' : string,
  'niche' : string,
}
export interface ContentItem {
  'id' : bigint,
  'status' : ContentStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'deadline' : [] | [Timestamp],
  'platform' : Platform,
  'updatedAt' : Timestamp,
  'userPrincipal' : UserId,
  'notes' : string,
}
export type ContentStatus = { 'Idea' : null } |
  { 'Posted' : null } |
  { 'Scheduled' : null } |
  { 'Scripting' : null } |
  { 'Editing' : null };
export interface DailyTask {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'createdDate' : Timestamp,
  'userPrincipal' : UserId,
}
export interface DashboardMetrics {
  'weeklyContentCount' : bigint,
  'productivityScore' : bigint,
  'focusHoursThisWeek' : number,
  'recentGenerations' : Array<AIGeneration>,
  'taskCompletionRate' : number,
  'contentStreak' : bigint,
  'nextScheduledContent' : [] | [ContentItem],
}
export type Platform = { 'Blog' : null } |
  { 'TikTok' : null } |
  { 'YouTube' : null } |
  { 'Other' : null } |
  { 'Instagram' : null } |
  { 'Twitter' : null };
export interface ProductivitySession {
  'id' : bigint,
  'completedAt' : Timestamp,
  'sessionType' : SessionType,
  'durationMinutes' : bigint,
  'userPrincipal' : UserId,
}
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Result_1 = { 'ok' : ContentItem } |
  { 'err' : string };
export type Result_2 = { 'ok' : ProductivitySession } |
  { 'err' : string };
export type Result_3 = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_4 = { 'ok' : AIGeneration } |
  { 'err' : string };
export type Result_5 = { 'ok' : DailyTask } |
  { 'err' : string };
export type SessionType = { 'Break' : null } |
  { 'Focus' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTier = { 'Pro' : null } |
  { 'Elite' : null } |
  { 'Free' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'displayName' : string,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'email' : string,
  'updatedAt' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'temperature' : number,
  'aiModel' : string,
  'darkMode' : boolean,
  'focusDuration' : bigint,
  'maxTokens' : bigint,
  'breakDuration' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createContentItem' : ActorMethod<
    [string, Platform, ContentStatus, [] | [Timestamp], string],
    Result_1
  >,
  'createDailyTask' : ActorMethod<[string, Timestamp], Result_5>,
  'createGeneration' : ActorMethod<[AIGenerationParams], Result_4>,
  'createOrUpdateUser' : ActorMethod<[string, string], Result_3>,
  'deleteContentItem' : ActorMethod<[bigint], Result>,
  'deleteDailyTask' : ActorMethod<[bigint], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listContentItems' : ActorMethod<[], Array<ContentItem>>,
  'listDailyTasks' : ActorMethod<[Timestamp], Array<DailyTask>>,
  'listGenerations' : ActorMethod<[], Array<AIGeneration>>,
  'listProductivitySessions' : ActorMethod<
    [bigint],
    Array<ProductivitySession>
  >,
  'logProductivitySession' : ActorMethod<[bigint, SessionType], Result_2>,
  'setOpenAIApiKey' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleDailyTask' : ActorMethod<[bigint], Result>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateContentItem' : ActorMethod<
    [bigint, string, Platform, ContentStatus, [] | [Timestamp], string],
    Result_1
  >,
  'updateGenerationFavorite' : ActorMethod<[bigint, boolean], Result>,
  'updateGenerationSaved' : ActorMethod<[bigint, boolean], Result>,
  'updateSubscriptionTier' : ActorMethod<
    [Principal, SubscriptionTier, string, string, Timestamp, Timestamp],
    Result
  >,
  'updateUserSettings' : ActorMethod<[UserSettings], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];