/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Platform = IDL.Variant({
  'Blog' : IDL.Null,
  'TikTok' : IDL.Null,
  'YouTube' : IDL.Null,
  'Other' : IDL.Null,
  'Instagram' : IDL.Null,
  'Twitter' : IDL.Null,
});
export const ContentStatus = IDL.Variant({
  'Idea' : IDL.Null,
  'Posted' : IDL.Null,
  'Scheduled' : IDL.Null,
  'Scripting' : IDL.Null,
  'Editing' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ContentItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : ContentStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'deadline' : IDL.Opt(Timestamp),
  'platform' : Platform,
  'updatedAt' : Timestamp,
  'userPrincipal' : UserId,
  'notes' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : ContentItem, 'err' : IDL.Text });
export const DailyTask = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'createdDate' : Timestamp,
  'userPrincipal' : UserId,
});
export const Result_5 = IDL.Variant({ 'ok' : DailyTask, 'err' : IDL.Text });
export const AIGenerationParams = IDL.Record({
  'goal' : IDL.Text,
  'tone' : IDL.Text,
  'audience' : IDL.Text,
  'platform' : IDL.Text,
  'niche' : IDL.Text,
});
export const AIGeneration = IDL.Record({
  'id' : IDL.Nat,
  'goal' : IDL.Text,
  'createdAt' : Timestamp,
  'tone' : IDL.Text,
  'audience' : IDL.Text,
  'platform' : IDL.Text,
  'saved' : IDL.Bool,
  'userPrincipal' : UserId,
  'niche' : IDL.Text,
  'outputText' : IDL.Text,
  'favorite' : IDL.Bool,
});
export const Result_4 = IDL.Variant({ 'ok' : AIGeneration, 'err' : IDL.Text });
export const SubscriptionTier = IDL.Variant({
  'Pro' : IDL.Null,
  'Elite' : IDL.Null,
  'Free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const Result_3 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const DashboardMetrics = IDL.Record({
  'weeklyContentCount' : IDL.Nat,
  'productivityScore' : IDL.Nat,
  'focusHoursThisWeek' : IDL.Float64,
  'recentGenerations' : IDL.Vec(AIGeneration),
  'taskCompletionRate' : IDL.Float64,
  'contentStreak' : IDL.Nat,
  'nextScheduledContent' : IDL.Opt(ContentItem),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SessionType = IDL.Variant({
  'Break' : IDL.Null,
  'Focus' : IDL.Null,
});
export const ProductivitySession = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : Timestamp,
  'sessionType' : SessionType,
  'durationMinutes' : IDL.Nat,
  'userPrincipal' : UserId,
});
export const Result_2 = IDL.Variant({
  'ok' : ProductivitySession,
  'err' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UserSettings = IDL.Record({
  'temperature' : IDL.Float64,
  'aiModel' : IDL.Text,
  'darkMode' : IDL.Bool,
  'focusDuration' : IDL.Nat,
  'maxTokens' : IDL.Nat,
  'breakDuration' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createContentItem' : IDL.Func(
      [IDL.Text, Platform, ContentStatus, IDL.Opt(Timestamp), IDL.Text],
      [Result_1],
      [],
    ),
  'createDailyTask' : IDL.Func([IDL.Text, Timestamp], [Result_5], []),
  'createGeneration' : IDL.Func([AIGenerationParams], [Result_4], []),
  'createOrUpdateUser' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
  'deleteContentItem' : IDL.Func([IDL.Nat], [Result], []),
  'deleteDailyTask' : IDL.Func([IDL.Nat], [Result], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listContentItems' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
  'listDailyTasks' : IDL.Func([Timestamp], [IDL.Vec(DailyTask)], ['query']),
  'listGenerations' : IDL.Func([], [IDL.Vec(AIGeneration)], ['query']),
  'listProductivitySessions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductivitySession)],
      ['query'],
    ),
  'logProductivitySession' : IDL.Func([IDL.Nat, SessionType], [Result_2], []),
  'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleDailyTask' : IDL.Func([IDL.Nat], [Result], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateContentItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Platform,
        ContentStatus,
        IDL.Opt(Timestamp),
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'updateGenerationFavorite' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
  'updateGenerationSaved' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
  'updateSubscriptionTier' : IDL.Func(
      [
        IDL.Principal,
        SubscriptionTier,
        IDL.Text,
        IDL.Text,
        Timestamp,
        Timestamp,
      ],
      [Result],
      [],
    ),
  'updateUserSettings' : IDL.Func([UserSettings], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Platform = IDL.Variant({
    'Blog' : IDL.Null,
    'TikTok' : IDL.Null,
    'YouTube' : IDL.Null,
    'Other' : IDL.Null,
    'Instagram' : IDL.Null,
    'Twitter' : IDL.Null,
  });
  const ContentStatus = IDL.Variant({
    'Idea' : IDL.Null,
    'Posted' : IDL.Null,
    'Scheduled' : IDL.Null,
    'Scripting' : IDL.Null,
    'Editing' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ContentItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : ContentStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'deadline' : IDL.Opt(Timestamp),
    'platform' : Platform,
    'updatedAt' : Timestamp,
    'userPrincipal' : UserId,
    'notes' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : ContentItem, 'err' : IDL.Text });
  const DailyTask = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'createdDate' : Timestamp,
    'userPrincipal' : UserId,
  });
  const Result_5 = IDL.Variant({ 'ok' : DailyTask, 'err' : IDL.Text });
  const AIGenerationParams = IDL.Record({
    'goal' : IDL.Text,
    'tone' : IDL.Text,
    'audience' : IDL.Text,
    'platform' : IDL.Text,
    'niche' : IDL.Text,
  });
  const AIGeneration = IDL.Record({
    'id' : IDL.Nat,
    'goal' : IDL.Text,
    'createdAt' : Timestamp,
    'tone' : IDL.Text,
    'audience' : IDL.Text,
    'platform' : IDL.Text,
    'saved' : IDL.Bool,
    'userPrincipal' : UserId,
    'niche' : IDL.Text,
    'outputText' : IDL.Text,
    'favorite' : IDL.Bool,
  });
  const Result_4 = IDL.Variant({ 'ok' : AIGeneration, 'err' : IDL.Text });
  const SubscriptionTier = IDL.Variant({
    'Pro' : IDL.Null,
    'Elite' : IDL.Null,
    'Free' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : SubscriptionTier,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const Result_3 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const DashboardMetrics = IDL.Record({
    'weeklyContentCount' : IDL.Nat,
    'productivityScore' : IDL.Nat,
    'focusHoursThisWeek' : IDL.Float64,
    'recentGenerations' : IDL.Vec(AIGeneration),
    'taskCompletionRate' : IDL.Float64,
    'contentStreak' : IDL.Nat,
    'nextScheduledContent' : IDL.Opt(ContentItem),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SessionType = IDL.Variant({ 'Break' : IDL.Null, 'Focus' : IDL.Null });
  const ProductivitySession = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : Timestamp,
    'sessionType' : SessionType,
    'durationMinutes' : IDL.Nat,
    'userPrincipal' : UserId,
  });
  const Result_2 = IDL.Variant({
    'ok' : ProductivitySession,
    'err' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UserSettings = IDL.Record({
    'temperature' : IDL.Float64,
    'aiModel' : IDL.Text,
    'darkMode' : IDL.Bool,
    'focusDuration' : IDL.Nat,
    'maxTokens' : IDL.Nat,
    'breakDuration' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createContentItem' : IDL.Func(
        [IDL.Text, Platform, ContentStatus, IDL.Opt(Timestamp), IDL.Text],
        [Result_1],
        [],
      ),
    'createDailyTask' : IDL.Func([IDL.Text, Timestamp], [Result_5], []),
    'createGeneration' : IDL.Func([AIGenerationParams], [Result_4], []),
    'createOrUpdateUser' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
    'deleteContentItem' : IDL.Func([IDL.Nat], [Result], []),
    'deleteDailyTask' : IDL.Func([IDL.Nat], [Result], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listContentItems' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
    'listDailyTasks' : IDL.Func([Timestamp], [IDL.Vec(DailyTask)], ['query']),
    'listGenerations' : IDL.Func([], [IDL.Vec(AIGeneration)], ['query']),
    'listProductivitySessions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductivitySession)],
        ['query'],
      ),
    'logProductivitySession' : IDL.Func([IDL.Nat, SessionType], [Result_2], []),
    'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleDailyTask' : IDL.Func([IDL.Nat], [Result], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateContentItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Platform,
          ContentStatus,
          IDL.Opt(Timestamp),
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'updateGenerationFavorite' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
    'updateGenerationSaved' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
    'updateSubscriptionTier' : IDL.Func(
        [
          IDL.Principal,
          SubscriptionTier,
          IDL.Text,
          IDL.Text,
          Timestamp,
          Timestamp,
        ],
        [Result],
        [],
      ),
    'updateUserSettings' : IDL.Func([UserSettings], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };