/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductivitySession {
    id: bigint;
    completedAt: Timestamp;
    sessionType: SessionType;
    durationMinutes: bigint;
    userPrincipal: UserId;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Result_2 = {
    __kind__: "ok";
    ok: ProductivitySession;
} | {
    __kind__: "err";
    err: string;
};
export interface ContentItem {
    id: bigint;
    status: ContentStatus;
    title: string;
    createdAt: Timestamp;
    deadline?: Timestamp;
    platform: Platform;
    updatedAt: Timestamp;
    userPrincipal: UserId;
    notes: string;
}
export type Result_5 = {
    __kind__: "ok";
    ok: DailyTask;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: ContentItem;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: AIGeneration;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface AIGenerationParams {
    goal: string;
    tone: string;
    audience: string;
    platform: string;
    niche: string;
}
export interface AIGeneration {
    id: bigint;
    goal: string;
    createdAt: Timestamp;
    tone: string;
    audience: string;
    platform: string;
    saved: boolean;
    userPrincipal: UserId;
    niche: string;
    outputText: string;
    favorite: boolean;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type Result_3 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface UserSettings {
    temperature: number;
    aiModel: string;
    darkMode: boolean;
    focusDuration: bigint;
    maxTokens: bigint;
    breakDuration: bigint;
}
export interface DashboardMetrics {
    weeklyContentCount: bigint;
    productivityScore: bigint;
    focusHoursThisWeek: number;
    recentGenerations: Array<AIGeneration>;
    taskCompletionRate: number;
    contentStreak: bigint;
    nextScheduledContent?: ContentItem;
}
export interface DailyTask {
    id: bigint;
    title: string;
    completed: boolean;
    createdDate: Timestamp;
    userPrincipal: UserId;
}
export interface UserProfile {
    principal: UserId;
    displayName: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    email: string;
    updatedAt: Timestamp;
}
export enum ContentStatus {
    Idea = "Idea",
    Posted = "Posted",
    Scheduled = "Scheduled",
    Scripting = "Scripting",
    Editing = "Editing"
}
export enum Platform {
    Blog = "Blog",
    TikTok = "TikTok",
    YouTube = "YouTube",
    Other = "Other",
    Instagram = "Instagram",
    Twitter = "Twitter"
}
export enum SessionType {
    Break = "Break",
    Focus = "Focus"
}
export enum SubscriptionTier {
    Pro = "Pro",
    Elite = "Elite",
    Free = "Free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createContentItem(title: string, platform: Platform, status: ContentStatus, deadline: Timestamp | null, notes: string): Promise<Result_1>;
    createDailyTask(title: string, date: Timestamp): Promise<Result_5>;
    createGeneration(params: AIGenerationParams): Promise<Result_4>;
    createOrUpdateUser(displayName: string, email: string): Promise<Result_3>;
    deleteContentItem(id: bigint): Promise<Result>;
    deleteDailyTask(id: bigint): Promise<Result>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardMetrics(): Promise<DashboardMetrics>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isOpenAIConfigured(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listContentItems(): Promise<Array<ContentItem>>;
    listDailyTasks(date: Timestamp): Promise<Array<DailyTask>>;
    listGenerations(): Promise<Array<AIGeneration>>;
    listProductivitySessions(limit: bigint): Promise<Array<ProductivitySession>>;
    logProductivitySession(durationMinutes: bigint, sessionType: SessionType): Promise<Result_2>;
    setOpenAIApiKey(key: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleDailyTask(id: bigint): Promise<Result>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateContentItem(id: bigint, title: string, platform: Platform, status: ContentStatus, deadline: Timestamp | null, notes: string): Promise<Result_1>;
    updateGenerationFavorite(id: bigint, favorite: boolean): Promise<Result>;
    updateGenerationSaved(id: bigint, saved: boolean): Promise<Result>;
    updateSubscriptionTier(target: Principal, tier: SubscriptionTier, stripeSubId: string, stripeCustomerId: string, periodStart: Timestamp, periodEnd: Timestamp): Promise<Result>;
    updateUserSettings(newSettings: UserSettings): Promise<Result>;
}
import type { AIGeneration as _AIGeneration, ContentItem as _ContentItem, ContentStatus as _ContentStatus, DailyTask as _DailyTask, DashboardMetrics as _DashboardMetrics, Platform as _Platform, ProductivitySession as _ProductivitySession, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, SessionType as _SessionType, StripeSessionStatus as _StripeSessionStatus, SubscriptionTier as _SubscriptionTier, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createContentItem(arg0: string, arg1: Platform, arg2: ContentStatus, arg3: Timestamp | null, arg4: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createContentItem(arg0, to_candid_Platform_n3(this._uploadFile, this._downloadFile, arg1), to_candid_ContentStatus_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContentItem(arg0, to_candid_Platform_n3(this._uploadFile, this._downloadFile, arg1), to_candid_ContentStatus_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDailyTask(arg0: string, arg1: Timestamp): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.createDailyTask(arg0, arg1);
                return from_candid_Result_5_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDailyTask(arg0, arg1);
            return from_candid_Result_5_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGeneration(arg0: AIGenerationParams): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createGeneration(arg0);
                return from_candid_Result_4_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGeneration(arg0);
            return from_candid_Result_4_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrUpdateUser(arg0: string, arg1: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUser(arg0, arg1);
                return from_candid_Result_3_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUser(arg0, arg1);
            return from_candid_Result_3_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContentItem(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentItem(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentItem(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDailyTask(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailyTask(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailyTask(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardMetrics(): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return from_candid_DashboardMetrics_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return from_candid_DashboardMetrics_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOpenAIConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOpenAIConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOpenAIConfigured();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listContentItems(): Promise<Array<ContentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContentItems();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContentItems();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDailyTasks(arg0: Timestamp): Promise<Array<DailyTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDailyTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDailyTasks(arg0);
            return result;
        }
    }
    async listGenerations(): Promise<Array<AIGeneration>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGenerations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGenerations();
            return result;
        }
    }
    async listProductivitySessions(arg0: bigint): Promise<Array<ProductivitySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductivitySessions(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductivitySessions(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async logProductivitySession(arg0: bigint, arg1: SessionType): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.logProductivitySession(arg0, to_candid_SessionType_n45(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_2_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logProductivitySession(arg0, to_candid_SessionType_n45(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_2_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async setOpenAIApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIApiKey(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleDailyTask(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDailyTask(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDailyTask(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateContentItem(arg0: bigint, arg1: string, arg2: Platform, arg3: ContentStatus, arg4: Timestamp | null, arg5: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentItem(arg0, arg1, to_candid_Platform_n3(this._uploadFile, this._downloadFile, arg2), to_candid_ContentStatus_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentItem(arg0, arg1, to_candid_Platform_n3(this._uploadFile, this._downloadFile, arg2), to_candid_ContentStatus_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGenerationFavorite(arg0: bigint, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGenerationFavorite(arg0, arg1);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGenerationFavorite(arg0, arg1);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGenerationSaved(arg0: bigint, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGenerationSaved(arg0, arg1);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGenerationSaved(arg0, arg1);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSubscriptionTier(arg0: Principal, arg1: SubscriptionTier, arg2: string, arg3: string, arg4: Timestamp, arg5: Timestamp): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionTier(arg0, to_candid_SubscriptionTier_n49(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionTier(arg0, to_candid_SubscriptionTier_n49(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserSettings(arg0: UserSettings): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserSettings(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserSettings(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContentItem_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentItem): ContentItem {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ContentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentStatus): ContentStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardMetrics_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardMetrics): DashboardMetrics {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ProductivitySession_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductivitySession): ProductivitySession {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_SessionType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionType): SessionType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentItem]): ContentItem | null {
    return value.length === 0 ? null : from_candid_ContentItem_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ContentStatus;
    title: string;
    createdAt: _Timestamp;
    deadline: [] | [_Timestamp];
    platform: _Platform;
    updatedAt: _Timestamp;
    userPrincipal: _UserId;
    notes: string;
}): {
    id: bigint;
    status: ContentStatus;
    title: string;
    createdAt: Timestamp;
    deadline?: Timestamp;
    platform: Platform;
    updatedAt: Timestamp;
    userPrincipal: UserId;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_ContentStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        deadline: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.deadline)),
        platform: from_candid_Platform_n15(_uploadFile, _downloadFile, value.platform),
        updatedAt: value.updatedAt,
        userPrincipal: value.userPrincipal,
        notes: value.notes
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    displayName: string;
    createdAt: _Timestamp;
    tier: _SubscriptionTier;
    email: string;
    updatedAt: _Timestamp;
}): {
    principal: UserId;
    displayName: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    email: string;
    updatedAt: Timestamp;
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        createdAt: value.createdAt,
        tier: from_candid_SubscriptionTier_n25(_uploadFile, _downloadFile, value.tier),
        email: value.email,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weeklyContentCount: bigint;
    productivityScore: bigint;
    focusHoursThisWeek: number;
    recentGenerations: Array<_AIGeneration>;
    taskCompletionRate: number;
    contentStreak: bigint;
    nextScheduledContent: [] | [_ContentItem];
}): {
    weeklyContentCount: bigint;
    productivityScore: bigint;
    focusHoursThisWeek: number;
    recentGenerations: Array<AIGeneration>;
    taskCompletionRate: number;
    contentStreak: bigint;
    nextScheduledContent?: ContentItem;
} {
    return {
        weeklyContentCount: value.weeklyContentCount,
        productivityScore: value.productivityScore,
        focusHoursThisWeek: value.focusHoursThisWeek,
        recentGenerations: value.recentGenerations,
        taskCompletionRate: value.taskCompletionRate,
        contentStreak: value.contentStreak,
        nextScheduledContent: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.nextScheduledContent))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completedAt: _Timestamp;
    sessionType: _SessionType;
    durationMinutes: bigint;
    userPrincipal: _UserId;
}): {
    id: bigint;
    completedAt: Timestamp;
    sessionType: SessionType;
    durationMinutes: bigint;
    userPrincipal: UserId;
} {
    return {
        id: value.id,
        completedAt: value.completedAt,
        sessionType: from_candid_SessionType_n43(_uploadFile, _downloadFile, value.sessionType),
        durationMinutes: value.durationMinutes,
        userPrincipal: value.userPrincipal
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Idea: null;
} | {
    Posted: null;
} | {
    Scheduled: null;
} | {
    Scripting: null;
} | {
    Editing: null;
}): ContentStatus {
    return "Idea" in value ? ContentStatus.Idea : "Posted" in value ? ContentStatus.Posted : "Scheduled" in value ? ContentStatus.Scheduled : "Scripting" in value ? ContentStatus.Scripting : "Editing" in value ? ContentStatus.Editing : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Blog: null;
} | {
    TikTok: null;
} | {
    YouTube: null;
} | {
    Other: null;
} | {
    Instagram: null;
} | {
    Twitter: null;
}): Platform {
    return "Blog" in value ? Platform.Blog : "TikTok" in value ? Platform.TikTok : "YouTube" in value ? Platform.YouTube : "Other" in value ? Platform.Other : "Instagram" in value ? Platform.Instagram : "Twitter" in value ? Platform.Twitter : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DailyTask;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DailyTask;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AIGeneration;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AIGeneration;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pro: null;
} | {
    Elite: null;
} | {
    Free: null;
}): SubscriptionTier {
    return "Pro" in value ? SubscriptionTier.Pro : "Elite" in value ? SubscriptionTier.Elite : "Free" in value ? SubscriptionTier.Free : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n36(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Break: null;
} | {
    Focus: null;
}): SessionType {
    return "Break" in value ? SessionType.Break : "Focus" in value ? SessionType.Focus : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProductivitySession;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ProductivitySession;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ProductivitySession_n41(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ContentItem;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ContentItem;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ContentItem_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentItem>): Array<ContentItem> {
    return value.map((x)=>from_candid_ContentItem_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductivitySession>): Array<ProductivitySession> {
    return value.map((x)=>from_candid_ProductivitySession_n41(_uploadFile, _downloadFile, x));
}
function to_candid_ContentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): _ContentStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Platform_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SessionType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): _SessionType {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    Blog: null;
} | {
    TikTok: null;
} | {
    YouTube: null;
} | {
    Other: null;
} | {
    Instagram: null;
} | {
    Twitter: null;
} {
    return value == Platform.Blog ? {
        Blog: null
    } : value == Platform.TikTok ? {
        TikTok: null
    } : value == Platform.YouTube ? {
        YouTube: null
    } : value == Platform.Other ? {
        Other: null
    } : value == Platform.Instagram ? {
        Instagram: null
    } : value == Platform.Twitter ? {
        Twitter: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): {
    Break: null;
} | {
    Focus: null;
} {
    return value == SessionType.Break ? {
        Break: null
    } : value == SessionType.Focus ? {
        Focus: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    Pro: null;
} | {
    Elite: null;
} | {
    Free: null;
} {
    return value == SubscriptionTier.Pro ? {
        Pro: null
    } : value == SubscriptionTier.Elite ? {
        Elite: null
    } : value == SubscriptionTier.Free ? {
        Free: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): {
    Idea: null;
} | {
    Posted: null;
} | {
    Scheduled: null;
} | {
    Scripting: null;
} | {
    Editing: null;
} {
    return value == ContentStatus.Idea ? {
        Idea: null
    } : value == ContentStatus.Posted ? {
        Posted: null
    } : value == ContentStatus.Scheduled ? {
        Scheduled: null
    } : value == ContentStatus.Scripting ? {
        Scripting: null
    } : value == ContentStatus.Editing ? {
        Editing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
